apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vos-ingress
  namespace: test-test
  selfLink: /apis/extensions/v1beta1/namespaces/test-test/ingresses/vos-test
spec:
  rules:
    - host: test.lijiahao.cool
      http:
        paths:
          - backend:
              serviceName: vos-svc
              servicePort: 80
            path: /
            pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
